- block:
  # sets up some custom bash aliases
  - import_tasks: system_setup/bash.yml

  # install and remove some software
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_utilities.yml

  # any remaining tasks:
  - import_tasks: system_setup/cron.yml

  rescue:
    - set_fact: task_failed=true
